# NumPy Basics

In [1]:
import numpy as np

## 1-D array

In [2]:
arr_from_list = np.array([1,3,5,7,9,111])
arr_from_tuple = np.array((11,13,51,71,92,98))

print(arr_from_list)
print(arr_from_tuple)
print(type(arr_from_list))

[  1   3   5   7   9 111]
[11 13 51 71 92 98]
<class 'numpy.ndarray'>


## 2-D Array, & Array properties

In [3]:
data = np.array([[1, 2], [3, 4], [5, 6], [20,30]])
print(data)

print('data.dtype=', data.dtype)
print('data.size=', data.size)
print('data.itemsize=', data.itemsize)

print('data.nbytes=', data.nbytes)

print('data.shape=', data.shape)
print('data.shape type', type(data.shape)) ##tuple
print('data.shape[0]=', data.shape[0])

print('data.ndim=', data.ndim)

print('data.strides=', data.strides)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [20 30]]
data.dtype= int64
data.size= 8
data.itemsize= 8
data.nbytes= 64
data.shape= (4, 2)
data.shape type <class 'tuple'>
data.shape[0]= 4
data.ndim= 2
data.strides= (16, 8)


### Creation with data type

In [4]:
np.arange(2,20, dtype=np.int8)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19], dtype=int8)

## 3-D Array & Access n-dim array item

In [5]:
a = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]] )

print(a)
print(type(a))
print(a.ndim) # how many subscripts needed to access this array 
print(a.shape)


print(a[1,0,2]) #access a item in array

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
3
(2, 2, 3)
3


## np arange, reshape, linspace

In [6]:
x = np.arange(50) # 0 to 49
print(x)
print("\n*****\n")

x = np.arange(20,100,3) # start stop and steps
print(x)
print("\n*****\n")

x = np.arange(50).reshape(5,2,5) # NOTE: shape passed as plain arguments
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]

*****

[20 23 26 29 32 35 38 41 44 47 50 53 56 59 62 65 68 71 74 77 80 83 86 89
 92 95 98]

*****

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]]]


In [7]:
# start at 10 stop at 20 included and get 15 evenly spaced points between with both included
np.linspace(10, 20, 15)

array([10.        , 10.71428571, 11.42857143, 12.14285714, 12.85714286,
       13.57142857, 14.28571429, 15.        , 15.71428571, 16.42857143,
       17.14285714, 17.85714286, 18.57142857, 19.28571429, 20.        ])

# zeroes, ones, empty array, identity matrix

In [8]:
z_m = np.zeros(3) # one dim zero matrix
print(z_m)

zero_matrix = np.zeros((4,2)) # NOTE: shape passed as list or tuple for dim > 1
zero_matrix

[0. 0. 0.]


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
np.zeros((2,3), dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [10]:
one_matrix = np.ones([5,3])
one_matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
empty_array = np.empty([2,3])
empty_array

array([[4.67938844e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [12]:
identity_matrix = np.eye(3) #takes only one arg since identity matrix is a square matrix of n x n
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])