# Random

In [1]:
import numpy as np

## random numbers

In [2]:
just_a_random_number = np.random.randint(20,100) # a random number between uppr and lower bounds
just_a_random_number

35

In [3]:
many_rand_numbers = np.random.randint(20,100, 10)
many_rand_numbers

array([55, 46, 97, 55, 88, 81, 50, 37, 41, 69])

In [4]:
# If you want seemingly random numbers, do not set the seed
# np.random.seed(4) 

In [5]:
#to prevent frequent use of np.random.randnt etc, another technique is to import like this
from numpy.random import randint
randint(10,20)

10

## random arrays

In [6]:
# Returns numbers from a random distribution

np.random.rand(2, 3) # note here the size is passed as args and not list or tuple

array([[0.1730882 , 0.38967044, 0.84642103],
       [0.70140133, 0.70584195, 0.5677551 ]])

In [7]:
np.random.randn(2,3) # returns random sample from standard normal distribution (centrered around 0)

array([[ 0.83217581, -0.22398663, -0.07472081],
       [-1.3078234 ,  0.19746968,  0.62640622]])

## Statistical methods on array

In [8]:
arr = np.random.randn(5,4)
print(arr)

print(arr.sum())
print (arr.max()), print(arr.argmax())
print(arr.min()), print(arr.argmin())
print(arr.mean()), print(arr.std())

[[-0.12918072  0.68608695 -0.6383845   1.87384002]
 [ 0.65533487 -0.35888399  1.16015638  0.80796952]
 [ 1.24504739  0.81741958 -0.25636287 -0.55336714]
 [-1.25026614  1.2128527   0.26072812  0.14692233]
 [-0.35099667 -0.06285367 -0.34383593 -2.02999459]]
2.8922316469702416
1.8738400240526718
3
-2.0299945946769427
19
0.14461158234851207
0.9117360039583022


(None, None)

In [9]:
arr2 = np.arange(0,12).reshape(4,3) # no mean and std in prior code snippet

arr2.mean(), arr2.std(), arr2.var()

(5.5, 3.452052529534663, 11.916666666666666)

## permutation with arranged sequence

In [10]:
x = np.random.permutation(np.arange(50))
print(x)

[21 28 38 33 47 32 14 13  2 46 26 10 43  6 27 49 25 15  7 18 17 20  1 29
 30 23 16 12 39  4  5  8 36 24 44  0 48 40 11 42 35 37 45  3 31 22 41  9
 19 34]


## Boolean Array

In [11]:
bool_arr = np.array([True, False, True])
print(bool_arr.any())
print(bool_arr.all())

True
False


In [12]:
country_arr = np.array(['Farnce', 'France', 'Germany', 'Germany', 'England'])
np.unique(country_arr)

array(['England', 'Farnce', 'France', 'Germany'], dtype='<U7')

## Add random seed and random state based config here