# Indexing, Selection and Masking

In [5]:
import numpy as np

## Indexed acces in 1-D Array

In [6]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr[6]

6

## Sliced array a view. Not a copy. 
Hence changes are broadcast in both ways

In [8]:
arr1 = np.arange(0,10)
sub_arr = arr[1:5] #sub_arr is a view
sub_arr

array([1, 2, 3, 4])

In [9]:
sub_arr[2] = 9999
arr

array([   0,    1,    2, 9999,    4,    5,    6,    7,    8,    9])

In [10]:
arr2 = np.arange(0,10) 
slice_arr = arr2[:] #view
print(slice_arr)
slice_arr[:] = 99
print(slice_arr)

[0 1 2 3 4 5 6 7 8 9]
[99 99 99 99 99 99 99 99 99 99]


## Indexed access in 2D Array

In [11]:
arr_2d = np.random.permutation(np.arange(0,20)).reshape(5,4)
arr_2d

array([[ 6,  7,  3,  4],
       [14, 17, 15, 10],
       [12,  2,  1, 19],
       [ 0,  5, 11,  8],
       [16, 13,  9, 18]])

In [12]:
arr_2d[0]

array([6, 7, 3, 4])

In [13]:
arr_2d[0][2] # double bracket notation

3

In [14]:
arr_2d[0,2] #single bracket notation

3

In [15]:
arr_2d = np.random.permutation(np.arange(0,20)).reshape(5,4)
arr_2d

array([[11, 10,  5, 17],
       [ 0, 18,  1, 15],
       [19,  8,  6, 16],
       [ 7,  4,  2,  9],
       [ 3, 13, 12, 14]])

In [16]:
#Getting second row
arr_2d[1,:]

array([ 0, 18,  1, 15])

In [17]:
#getting second column
b[:, 1]

NameError: name 'b' is not defined

In [ ]:
#sub matrix
arr_2d[:3,2:]

In [ ]:
# find the index of a particular value
idx = np.argwhere(arr_2d == 5)

print(idx)

print(idx[0][0])

## Masking
1. with list or 
2. conditional with Array 
NOTE: both produce copy

In [ ]:
sub_arr2 = arr[[1,3,4]] #input an indexed list of indexes
sub_arr2 #sub_arr2 is A COPY

In [ ]:
arr_2d = np.random.permutation(np.arange(0,20)).reshape(5,4)
arr_2d

In [ ]:
arr_bool = arr_2d > 5
arr_bool

In [ ]:
arr_2d[arr_bool] # Note: Loses dimensionality, also this is a copy

In [ ]:
#one step to do this both
arr_2d[arr_2d>5]

In [ ]:
# & and
# | or
# ~ not
# use former between arrays latter between objects

arr_2d[ (arr_2d>5) & (arr_2d < 12)]

## np.where() to retain same dimensionality in masking
you are going to need a fill value. In the example below I use 0, but you could also use np.nan

In [ ]:
np.where(arr_2d > 5, arr_2d, 0) # 2nd and 3rd arg are if else for condition

## Conditional zipping

In [ ]:
A = np.array([1,2,3,4])
B = np.array([100, 200, 300, 400])
condition = np.array([True, True, False, False])
answer = [A_val if cond else B_val for A_val, B_val, cond in zip(A,B,condition)]
answer