# Vector and Matrix operations

In [3]:
import numpy as np

## Scalar Multiplication

In [12]:
arr= np.random.rand(3,4)
arr

array([[0.4157608 , 0.34803992, 0.35474137, 0.58147941],
       [0.23432469, 0.97113952, 0.25795855, 0.87100879],
       [0.61946584, 0.84411447, 0.74181319, 0.38142814]])

In [13]:
arr = arr * 100
arr

array([[41.57607958, 34.80399152, 35.47413706, 58.14794065],
       [23.43246941, 97.11395185, 25.79585453, 87.10087854],
       [61.94658412, 84.4114473 , 74.18131923, 38.14281383]])

In [29]:
arr = arr **2
arr

array([[  9,  49,  16,   1],
       [ 64, 144, 121,  81],
       [ 36,  25,   4, 100]])

## Scalar addition

In [28]:
arr= np.random.permutation(np.arange(1,13)).reshape(3,4)
print(arr)

arr + 10

[[ 3  7  4  1]
 [ 8 12 11  9]
 [ 6  5  2 10]]


array([[13, 17, 14, 11],
       [18, 22, 21, 19],
       [16, 15, 12, 20]])

## Vector/Matrix Addition

In [26]:
arr = np.random.permutation(np.arange(1,13)).reshape(3,4)
print(arr)

arr_new = arr + arr
arr_new

[[ 1  8 10  3]
 [ 9  7  6  4]
 [11  5  2 12]]


array([[ 2, 16, 20,  6],
       [18, 14, 12,  8],
       [22, 10,  4, 24]])

In [1]:
A = np.arange(1, 7).reshape(2,3)
print(A)

A+np.arange(2).reshape(2,1)

NameError: name 'np' is not defined

## Matrix multiplication of corresponding elements only

In [38]:
arr1 = np.arange(0,9).reshape(3,3)
arr2 = np.arange(12,21).reshape(3,3)
arr3 = arr1 * arr2
arr3

array([[  0,  13,  28],
       [ 45,  64,  85],
       [108, 133, 160]])

In [6]:
A = np.arange(0,10).reshape(2,5)
B = np.arange(8,18).reshape(2,5)
C = A**B
C

array([[                0,                 1,              1024,
                   177147,          16777216],
       [       1220703125,       78364164096,     4747561509943,
          281474976710656, 16677181699666569]])

## Matrix Division

In [40]:
arr4 = 1/arr3 #Note division by zero
arr4

<ipython-input-40-4186f924b6f3>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr4 = 1/arr3 #Note division by zero


array([[       inf, 0.07692308, 0.03571429],
       [0.02222222, 0.015625  , 0.01176471],
       [0.00925926, 0.0075188 , 0.00625   ]])

## Sorting

In [18]:
arr.sort(axis=0)
arr

array([[23., 35., 26., 38.],
       [42., 84., 35., 58.],
       [62., 97., 74., 87.]])

## Universal Functions

In [ ]:
arr = np.round(arr)
arr

In [30]:
arr = np.sqrt(arr)
arr

array([[ 3.,  7.,  4.,  1.],
       [ 8., 12., 11.,  9.],
       [ 6.,  5.,  2., 10.]])

In [31]:
np.max(arr) # same as arr.max()

12.0

In [32]:
#np.exp(arr)

array([[2.00855369e+01, 1.09663316e+03, 5.45981500e+01, 2.71828183e+00],
       [2.98095799e+03, 1.62754791e+05, 5.98741417e+04, 8.10308393e+03],
       [4.03428793e+02, 1.48413159e+02, 7.38905610e+00, 2.20264658e+04]])

In [36]:
np.sin(arr)

array([[ 0.14112001,  0.6569866 , -0.7568025 ,  0.84147098],
       [ 0.98935825, -0.53657292, -0.99999021,  0.41211849],
       [-0.2794155 , -0.95892427,  0.90929743, -0.54402111]])

In [37]:
np.log(arr)

array([[1.09861229, 1.94591015, 1.38629436, 0.        ],
       [2.07944154, 2.48490665, 2.39789527, 2.19722458],
       [1.79175947, 1.60943791, 0.69314718, 2.30258509]])

### Binary functions

In [51]:
A = np.random.randn(10)
print(A)

B = np.random.randn(10)
print(B)

np.add(A,B)

[ 0.29753288 -1.38283298 -0.53489753 -1.66905272 -1.57153333  0.73583771
 -1.59696065 -1.42832441  0.21389511  0.03486821]
[ 1.71507597  0.23686     0.92421494 -0.05170157  1.38841015 -0.32120813
 -0.83929183 -0.29721859 -0.40421858 -0.12019839]


array([ 2.01260885, -1.14597297,  0.38931742, -1.72075429, -0.18312318,
        0.41462958, -2.43625248, -1.725543  , -0.19032347, -0.08533018])

In [52]:
np.maximum(A,B)

array([ 1.71507597,  0.23686   ,  0.92421494, -0.05170157,  1.38841015,
        0.73583771, -0.83929183, -0.29721859,  0.21389511,  0.03486821])

## Transpose

In [50]:
arr.T

array([[ 3.,  8.,  6.],
       [ 7., 12.,  5.],
       [ 4., 11.,  2.],
       [ 1.,  9., 10.]])

In [47]:
arr_3d = np.arange(60).reshape(5,4,3)
arr_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47]],

       [[48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59]]])

In [42]:
arr_3d.T

array([[[ 0, 10, 20, 30, 40],
        [ 2, 12, 22, 32, 42],
        [ 4, 14, 24, 34, 44],
        [ 6, 16, 26, 36, 46],
        [ 8, 18, 28, 38, 48]],

       [[ 1, 11, 21, 31, 41],
        [ 3, 13, 23, 33, 43],
        [ 5, 15, 25, 35, 45],
        [ 7, 17, 27, 37, 47],
        [ 9, 19, 29, 39, 49]]])

## Imp info about 3d transpose

In [48]:
arr_3d.transpose(1,0,2) #transpose method takes a tuple

array([[[ 0,  1,  2],
        [12, 13, 14],
        [24, 25, 26],
        [36, 37, 38],
        [48, 49, 50]],

       [[ 3,  4,  5],
        [15, 16, 17],
        [27, 28, 29],
        [39, 40, 41],
        [51, 52, 53]],

       [[ 6,  7,  8],
        [18, 19, 20],
        [30, 31, 32],
        [42, 43, 44],
        [54, 55, 56]],

       [[ 9, 10, 11],
        [21, 22, 23],
        [33, 34, 35],
        [45, 46, 47],
        [57, 58, 59]]])

## Must read to understand the transpose

https://stackoverflow.com/questions/32034237/how-does-numpys-transpose-method-permute-the-axes-of-an-array

In [49]:
arr_3d.swapaxes(0,1)

array([[[ 0,  1,  2],
        [12, 13, 14],
        [24, 25, 26],
        [36, 37, 38],
        [48, 49, 50]],

       [[ 3,  4,  5],
        [15, 16, 17],
        [27, 28, 29],
        [39, 40, 41],
        [51, 52, 53]],

       [[ 6,  7,  8],
        [18, 19, 20],
        [30, 31, 32],
        [42, 43, 44],
        [54, 55, 56]],

       [[ 9, 10, 11],
        [21, 22, 23],
        [33, 34, 35],
        [45, 46, 47],
        [57, 58, 59]]])

In [53]:
website = 'https://numpy.org/doc/stable/reference/'
import webbrowser
webbrowser.open_new(website)

True