# hstack vstack

In [1]:
import numpy as np

In [2]:
A = np.arange(1, 7).reshape(2,3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
B = np.arange(12,8,-1).reshape(2,2)
B

array([[12, 11],
       [10,  9]])

In [10]:
C = np.hstack((A,B))
C

array([[ 1,  2,  3, 12, 11],
       [ 4,  5,  6, 10,  9]])

## newaxis squeeze

In [ ]:
#nothing here as of now