# Load and Save

In [1]:
import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.save('myarray', arr)

In [5]:
np.load('myarray.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr2 = np.arange(5)
np.savez('ziparray.npz', x=arr, y=arr2)

In [15]:
archive_array = np.load('ziparray.npz')
archive_array

In [16]:
archive_array['x']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.savetxt('mytextarray.txt', arr2, delimiter=',')

In [19]:
arrx = np.loadtxt('mytextarray.txt', delimiter=',')
arrx

array([0., 1., 2., 3., 4.])